salt/pi/asound.conf, salt/pi/basics.sls, salt/pi/config.txt, salt/pi/thermal-recorder/thermal-recorder.yaml.jinja
Added support for i2s audio. Added LED pins to thermal-recorder.yaml so they don't interfere with the audio i2s pins.
=> Added support for i2s audio

salt/pi/management-interface/init.sls, salt/pi/thermal-recorder/init.sls, salt/top.sls
Added management-interface and updated thermal-recorder so the snapshot function works.
=> Add management interface

salt/pi/attiny-controller/init.sls, salt/pi/basics.sls, salt/pi/rsyslog
- Restart attiny-controller when config file is changed.
- Keep logs for 31 days
=> Watch attiny controller file and extend logs

salt/pi/thermal-recorder/init.sls, salt/pi/thermal-recorder/thermal-recorder.yaml.jinja
Added the throttler to thermal-recorder
=> Add throttler.

salt/pi/thermal-recorder/init.sls, salt/pi/thermal-recorder/thermal-recorder-1.11.yaml.jinja
... and remove some config which is no longer used.
=> Bump thermal-recorder to 1.12

salt/top.sls
At google SMTP enabled access for them
=> Mail relay also for test servers

salt/pi/thermal-recorder/init.sls, salt/pi/thermal-uploader/init.sls
=> thermal-recorder 1.15.1 and thermal-uploader 1.6

salt/pi/thermal-recorder/init.sls, salt/pi/thermal-uploader/init.sls
Get these deployed everywhere. 
This brings in CPTV v2 support
=> thermal-recorder 1.15.1 & thermal-uploader 1.6

salt/server/grafana/map.jinja
Grafana 5.4.1 has extra options, among which 'Disable Resolve Message'
=> Grafana update in test

salt/server/telegraf/map.jinja
update of telegraf worked and new graphs are made:
https://dashboard-test.cacophony.org.nz/d/yUpuRsliz/processes?orgId=1&from=now-12h&to=now
https://dashboard-test.cacophony.org.nz/d/oi1Zi6Bmzd/quick-overview?refresh=30s&orgId=1
=> telegraf update worked in test

salt/server/tools/map.ninja, salt/server/tools/mc.sls, salt/top.sls
Managing minio client versions. First for test.
=> Adding minio client under version control

salt/server/tools/map.jinja, salt/top.sls
mistakes in copying by hand fixed
=> Spelling mistakes, and prod added

salt/server/basics.sls, salt/server/tools/ffmpeg.sls, salt/top.sls
adding basic packages:
https://tree.taiga.io/project/the-cacophony-project/us/663?kanban-status=268960
and get mc on api-server
=> Adding basic packages

salt/top.sls
Managing minio-server with salt. Test on _server-test-api_ as it keeps the current config.
=> Tested minio server with salt

salt/server/tools/map.jinja
=> Version fixed

salt/server/grafana/map.jinja, salt/server/telegraf/map.jinja, salt/server/tools/map.jinja
https://tree.taiga.io/project/the-cacophony-project/us/642?kanban-status=268962
=> upgrades tested

salt/server/grafana/grafana.ini.jinja, salt/server/grafana/init.sls, salt/server/grafana/map.jinja
=> grafana.ini managed per server

salt/pi/thermal-recorder/thermal-recorder.yaml.jinja
As has been running on livingsprings02 for a while
=> Increase video throttling

salt/pi/thermal-recorder/init.sls, salt/pi/thermal-recorder/thermal-recorder.yaml.jinja
updated thermal-recorder beta version to 1.16
=> updated thermal-recorder to use sunrise-sunset window

salt/pi/thermal-recorder/thermal-recorder.yaml.jinja
, and re added window start/stop time in for non beta recorders
=> added recorder-no-window grain

salt/pi/thermal-recorder/thermal-recorder.yaml.jinja
Some locations need a fixed recording window instead of being based on sunrise/sunset.
=> Allow manual recording window as an option to sunrise/sunset

salt/pi/thermal-recorder/init.sls, salt/pi/thermal-recorder/thermal-recorder.yaml.jinja
The sunset-sunrise recording window feature is confirmed to be working well on beta devices so get this out everywhere.
=> Roll out thermal-recorder 1.16.1

tools/salt-auto-update.py
This is to support checking whether an auto-update was successful.
=> salt-auto-update: Store job id when scheduling update

salt/pi/audiobait/init.sls, salt/pi/event-reporter.sls, salt/pi/management-interface/init.sls
- audiobait 1.1.0
- event-reporter 1.1.0
- management-interface 0.8
All tested on a pi
=> Various package updates

salt/pi/thermal-recorder/init.sls, salt/pi/thermal-recorder/thermal-recorder-beta.yaml.jinja
- v1.19.0 promoted from beta to general access
- v1.20.0 to beta device (throttling fixes)
- added grain to allow throttling to be enabled and disabled
=> thermal-recorder updates

pi/thermal-recorder/init.sls, pi/thermal-recorder/thermal-recorder.yaml.jinja
- Make throttling a little less aggressive
- Bump temp threshold to 2900
- Release thermal-recorder 1.21.0
=> thermal-recorder v1.21.0 

pi/device-register.sls
Also removed an unused param to service.enabled.
=> device-register v0.3

pi/rtc/init.sls
Update rtc-utils to 1.2.0
Visual only.
Not required.
=> Bump rtc-utils to 1.2.0

pi/management-interface/init.sls, pi/maybe-reboot.sls, pi/rtc/init.sls, pi/salt-minion/check-salt-keys, pi/salt-minion/check-salt-keys.cron, pi/salt-minion/init.sls, pi/salt-minion/minion, pi/salt-minion/override.conf
Take last week's testing change to prod.
I have checked these changes on various test devices.
Not required.
=> Weekly merge of test to prod

pi/event-reporter.sls, pi/rtc/init.sls
Weekly releases to test.
- Bump event-reporter to 2.2.0
- Bump rtc-utils to 1.3.0
Tested on dev pi.
Not required.
=> Weekly update

pi/thermal-recorder/init.sls
=> Pull in thermal-recorder bugfix

pi/config/init.sls, pi/management-interface/init.sls
=> Bump managementd and cacophony-config

pi/management-interface/init.sls
Update management-interface to fix bug with new audiobait page.
Manual verification.
Not required.
=> Bump management interface to 1.2.1

pi/basics.sls
Remove old HDMI service from basics.sls
NA
=> Removed old hdmi service

pi/thermal-recorder/init.sls
=> Bump thermal-recorder to 2.1.3

top.sls
Start using the energy-savings script for production pis.
Not tested (copied from test)
N.A.
=> Add energy-savings for prod pis

server/basics.sls
Required for upcoming audio-analysis deployment
Tested on a test server
N.A.
=> Install Docker on all servers

pi/attiny-controller/init.sls
Update attiny-controller to 3.2.0
NA
=> Updated attiny-controller to 3.2.0

pi/attiny-controller/init.sls, pi/config/init.sls, server/basics.sls, server/hosts.jinja
Weekly merge test branch into prod.
All changes manually reviewed or already checked on test devices/servers.
N.A.
=> Weekly merge of test into prod

pi/config/init.sls
Update `cacophony-config` to 1.3.1
NA
=> udpate cacophony-config to 1.3.1

top.sls
=> Added start and end to test pis

pi/config/init.sls
=> Upgrade prod config

pi/event-reporter.sls
=> Bump event-reporter to 2.3.0

.github/pull_request_template.md, pi/end/init.sls, pi/event-reporter.sls, pi/start/init.sls, pi/start/stay-on, pi/start/stay-on.service, salt/.gitignore, salt/top.sls, state-apply-test.sh
- keep devices turned on during updates
- event-reporter persistence fix
Merge of already tested features. Ran test update against test devices and manually verified correct operation.
Required for "stay on" changes.
=> Weekly merges of test into prod

top.sls
This makes updates safer. Porting changes from test to prod. Required for #158
Visual verification.
=> Tell attiny & modemd to keep device & link up during updates (prod)

server/basics.sls
Our servers have a bunch of unnecessary packages installed. This PR removes some of them to free up disk space.
Manually tested on server-test-processing02.
N.A.
=> Remove unnecessary packages from servers

pi/attiny-controller/attiny.yaml.jinja, pi/attiny-controller/init.sls, pi/management-interface/init.sls, pi/thermal-recorder/init.sls, pi/thermal-uploader/init.sls
Various updates to test.
Tested against a local pi using Cam's excellent script.
N.A.
=> Weekly releases to test

pi/attiny-controller/attiny.yaml.jinja, pi/attiny-controller/init.sls, pi/management-interface/init.sls, pi/thermal-recorder/init.sls, pi/thermal-uploader/init.sls, server/basics.sls
Regular merge of test to prod.
Manual review of changes only.
N.A.
=> Merge test to prod

pi/end/init.sls
- Save time of last salt update on device
NA
=> Record time of last salt update

pi/management-interface/init.sls, pi/thermal-recorder/init.sls
Weekly release of packages.
Tested on dev device.
N.A.
=> Update management-interface and thermal-recorder

pi/management-interface/init.sls, pi/thermal-recorder/init.sls
Weekly package updates.
Manual inspection. Just tested on "dev" branch.
N.A.
=> Test update

pi/management-interface/init.sls
Upgrade managementd to 1.5.0
NA
=> Upgrade managementd to 1.5.0

pi/management-interface/init.sls
Update management interface to v1.6.0
NA
NA
=> updated management interface to v1.6.0

pi/event-reporter.sls
=> updated event reporter to 3.0.0

pi/event-reporter.sls
Update event-reporter to 3.0.0
NA
NA
=> Test event

pi/thermal-recorder/init.sls
- Update thermal-recorder to 2.5.0
NA
=> Update thermal-recorder to 2.5.0

pi/event-reporter.sls
- Upgrade event-reporter to fix migration error
NA
=> Update event-reporter to 3.1.0

pi/event-reporter.sls
Update event-reporter to fix migration bug
NA
=> Upgrade event-reporter to 3.1.0

top.sls
Added new branches for updating feverfinder pis. 
Not tested yet. 
Added the new branches.  Still a lot of work to do on individual branches.
=> Added fever branches to deployment.

pi/feverscreen/init.sls
Update feverscreen to 0.2.1
NA
=> update feverscreen to 0.2.1

pi/feverscreen/init.sls
=> update feverscreen to 0.3.1

top.sls
- Add salt-migration section to fever-test
=> Added section for salt migration

top.sls
- Add salt migration to test and fever
NA
NA
=> Add salt migration to test and fever

server/salt.sls
Update source for salt 
Tested on test-api server
NA
=> Use latest salt source

server/salt.sls
Update salt source
Tested on test-api
NA
=> Salt source test

top.sls
Add salt migration to prod servers and PIs
=> Add salt migration to prod servers and pis

pi/feverscreen/init.sls
Update feverscreen to 0.5.1
Tested on my test device
NA
=> Updated feverscreen version to 0.5.1

pi/feverscreen/init.sls
Update feverscreen version to 0.5.1
Tested on test branch
NA
=> Update fever prod

pi/feverscreen/init.sls
Update feverscreen to 0.5.3
NA
=> Updated feverscreen to 0.5.3

pi/removed.sls, pi/salt-minion/init.sls, salt/top.sls
Fix some small things causing errors
NA
=> Update salt repo

pi/attiny-controller/init.sls, pi/audiobait/init.sls, pi/thermal-recorder/init.sls, state-apply-test.sh
Update:
- attiny-controller
- audiobait
- thermal-recorder 
Tested on my RPi.
NA
=> Window location fix

README.md
Add small bit of documentation for update process
NA
NA
=> Add readme for helping update process

top.sls
Add dev-pis for making testing quick changes in the field much easier.
Will wait until it's merged and will test it on the salt server
NA
=> Added dev-pis

pi/wpa.sls, state-apply-test.sh
Fix error causing new lines getting added every salt update 
NA
=> Fix wpa file

top.sls
=> Added salt-updater

pi/salt-updater/init.sls, salt/top.sls
Added salt-updater
Tested on my own device
Please include a references to any related PRs. https://github.com/TheCacophonyProject/saltops/pull/233
=> Added salt-update

.github/workflows/aggregate-versions.js, .github/workflows/aggregate-versions.yml, README.md, pi/attiny-controller/init.sls, pi/dev-pis/init.sls, pi/event-reporter.sls, pi/management-interface/init.sls, pi/prod-pis/init.sls, pi/salt-updater/init.sls, pi/test-pis/init.sls, pi/thermal-recorder/init.sls, pi/wpa.sls, salt/top.sls, state-apply-test.sh
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
=> Move dev forward

pi/audiobait/init.sls
- Updated audiobait to version 2.2.1
Tested on my camera 
NA
=> Updaed audiobait to version 2.2.1

pi/thermal-recorder/init.sls
- Update thermal-recorder to 2.12.0
NA
=> Update thermal-recorder to 2.12.0

pi/thermal-recorder/init.sls
Added check for zero value pixels outside of the edged area
Test on my pi with zero pixels being generated
=> up thermal recorder version

pi/device-register.sls
Updated device-register to 1.3.0
NA
=> Updated device-register to 1.3.0

top.sls
- Added salt-updater to test devices. This has been on dev devices for a while but the top.sls in master was not updated when dev was pushed to test
=> Added salt-updater to test pis

pi/thermal-recorder/init.sls
Remove old mount point that is no longer used
NA
=> Remove old unused mount point

pi/management-interface/init.sls, pi/salt-updater/init.sls
- Update salt-updater to v0.4.0
- Update managment-interface to v1.9.0
- 
NA
=> Update salt updater and management-interfce

top.sls
- Adding salt-updater to prod devices
- Added nodegroup details to prod devices
=> Added salt-updater to prod devices

pi/thermal-uploader/init.sls
Adds file hash to uploaded recordings
N/A
=> update uploader version

pi/device-register.sls
- Updated device-register to 1.4.0
NA
=> Update device-register to 1.4.0

pi/modemd/init.sls
=> Updated modemd to 1.2.3

pi/config/init.sls
- Updated go-config to 1.6.4
NA
=> Update go-config to 1.6.4

pi/thermal-recorder/init.sls
- Updated thermal-recorder to 2.14.0
NA
=> Updated thermal-recorder to 2.14.0

.github/workflows/aggregate-versions.yml
- Only run aggregate version on dev branch
=> Only run aggregate version on dev branch

pi/management-interface/init.sls, pi/thermal-recorder/init.sls
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
=> update recorder and management versions

pi/event-reporter.sls, pi/management-interface/init.sls
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
=> update mgmnt and event

top.sls
Reverts TheCacophonyProject/saltops#277
Remove test changes added to debug gitfs
=> Revert "Update top.sls"

pi/apt-updater/apt-updater-script
Added events to report apt--get update and apt-get upgrade failures
Tested by forcing failures of apt-get upgrade and verifying error event received by server
- [ No] Does this change require an update to top.sls in the `master` branch?
=> Add apt update events

top.sls
Added apt-update to prod devices
Tested on test devices
NA
=> Add apt-updater to top.sls for prod devices

pi/config/init.sls, pi/management-interface/init.sls
Updated managementd and co-config to fix issue with wrong time windows.
NA
=> Update so invalid time windows can't be set

pi/management-interface/init.sls, pi/thermal-recorder/init.sls
- Updated thermal-recorder and managementd to new version to allow for making snapshots
Tested on my camera
NA
=> Added snapshot updates for thermal-recorder and managementd

pi/attiny-controller/init.sls, pi/modemd/init.sls
Update modemd to only be connected when a dns lookup succeeds
Upgrade attiny to retry authentication 3 times
=> update modemd and attiny

pi/attiny-controller/init.sls, pi/management-interface/init.sls, pi/modemd/init.sls
Updates are both fixes.
Running on two devices one with a modem, seems to have no error anymore due to fix.
=> Update attiny-controller, management-interface, modemd

pi/attiny-controller/init.sls, pi/modemd/init.sls, state-apply-test-rpi.sh
- Update modemd
- Update attiny-controller
Tested on my camera
NA
=> Update modemd attiny

pi/modemd/init.sls
Install required dnsutils so that we can check a connection to a dns server
=> install dns utils

pi/modemd/init.sls
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
=> install dns utils (#310)

pi/start/init.sls
=> Run apt-get update

server/users.sls
Added ability to manage users passwords using salt.
Tested on new salt master server
NA
=> Manage users passwords also using salt

top.sls
Remove `server/salt` from prod
=> Remove  from prod

pi/attiny-controller/init.sls, pi/event-reporter.sls, pi/modemd/init.sls, pi/salt-updater/init.sls
Update packages to trigger events on modem connection 
NA
=> Update modemd, attiny, salt-updater, and event-reporter

pi/thermal-recorder/init.sls
Update thermal recorder to 2.18.1 where thermal-recorder will restart when the recording window has updated.
Tested on my device.
NA
=> Update thermal-recorder to 2.18.1

top.sls
Adding TC2 to the top.sls so they can be managed through salt.
=> Added tc2 to top.sls

tc2/basics/new-image-tidy.sh, tc2/management-interface/init.sls, tc2/modemd/init.sls, tc2/tc2-hat-controller/init.sls
=> Updated tc2 packages

tc2/tc2-hat-controller/init.sls, tc2/thermal-recorder-py/init.sls
Updated tc2-hat package and disable old therma-recorder
Tested on my own device
NA
=> Updated tc2-hat-controller

tc2/tc2-agent/init.sls
Temp fix for lepton3.5 sensors 
Tested on my camera
NA
=> Temp fix for tc2-agnet on lepton3.5 sensors

top.sls
Updating the top file for the latest tc2 changes.
=> Update top file for tc2 changes
