salt/_states/cacophony.py, salt/pi/attiny-controller/init.sls, salt/pi/audiobait/init.sls, salt/pi/event-reporter.sls, salt/pi/management-interface/init.sls, salt/pi/thermal-recorder/init.sls, salt/pi/thermal-uploader/init.sls
Version numbers were being converted to floating point values during
YAML parsing which caused cacophony.pkg_installed_from_github to not
think the correct version of a package was installed and therefore
download it again.
All version numbers in states have been forced to strings and
pkg_installed_from_github now asserts that the version number it gets is
a string.
On an up-to-date pi with a good network connection this brings the
state.apply time down from 61.7s to 11.9s.
=> Prevent packages being downloaded unnecessarily

salt/pi/thermal-recorder/init.sls, salt/pi/thermal-recorder/thermal-recorder-1.11.yaml.jinja, salt/pi/thermal-recorder/thermal-recorder.yaml.jinja
Devices with `cacophony:recorder-beta` set will receive thermal-recorder 1.11.  This is the first version to use the Lepton telemetry data.
A `cacophony:recorder-preview` grain has also been added. This lets us set the thermal-recorder preview time on a per device basis.
=> thermal-recorder 1.11 and introduce new grains

salt/server/telegraf/map.jinja
The newest *telegraf* has de plugin procstat_lookup, with which you can monitor number of processes per application. We than can make an alert when it is zero.
=> newest version telegraf, for monitoring processes handy

salt/server/salt.sls, salt/server/tools/map.jinja, salt/server/tools/minio.config, salt/server/tools/minio.service, salt/server/tools/minio.sls
This minio-server installation should preserve current version *and* config (replace:false). But it is a valid installation set of it self.
The use of 'minio-user' for the process is by-passed, and in line with the current implementation it is all as user 'root'.
=> minio server

salt/server/influxdb/map.jinja, salt/top.sls
InfluxDB Version  1.7.4 is tested on test-api for Grafana/Telegraf. Should be tested for the 'devices' that use it also, before proceeding to production. But we don't have that in test I think.
=> InfluxDB now managed also in production, and upgraded

salt/pi/rsyslog
Increase time logs are kept from 4 to 30 weeks.
=> Increase time logs are kept

salt/pi/thermal-recorder/thermal-recorder.yaml.jinja
The indentation before the option was being removed.
=> Fix whitespace issue for `sunrise-sunset` field

tools/salt-auto-update.py, tools/salt-auto-update.service, tools/salt-presence.py, tools/salt_listener.py
The new salt-auto-update service automatically schedules a `state.apply` when minions connect to the salt master, unless they've already received an update in the last 23 hrs.
A blacklist file at /etc/salt/autoupdate.blacklist can be used to prevent auto updates of specific devices.
As part of this the logic for listening to the salt-master events was abstracted. The salt-presence services now uses this too (and was cleaned up a little in the process).
=> Implement auto update service for Raspberry Pis

salt/pi/thermal-recorder/init.sls, salt/pi/thermal-recorder/thermal-recorder.yaml.jinja
With new `cacophony:recorder-motion-debug` grain to enable motion detection debugging feature.
=> thermal-recorder 1.18.0 for beta devices

salt/pi/wpa.sls
This means that when connecting to a wifi network if a "bushnet" wifi is available it will try to connect to that first.
=> Change priority of bushnet wifi

salt/pi/audiobait/init.sls, salt/pi/thermal-uploader/init.sls
The thermal-uploader update creates device.yaml if it's not already present.
=> audiobait to 1.2.0 and thermal-uploader to 1.7

salt/pi/salt-minion/init.sls, salt/pi/salt-minion/override.conf
Will prevent salt-minion.service from running if there is no minion_id file.
=> Wait for minion_id

salt/pi/thermal-recorder/init.sls, salt/pi/thermal-recorder/thermal-recorder.yaml.jinja
* Set more sensitve motion detection params. These have been working well on akaroa24 and cam-test-04.
* Roll out thermal-recorder 1.18.0 everywhere
=> thermal recorder to 1.18.0 and more sensitive motion detection

salt/pi/basics.sls, salt/pi/config.txt, salt/pi/config.txt.jinja
- fix pin for thermal camera, helping the RTC load properly
- Have USB power on by default (will help when loading the USB modem)
When the pins are not set at boot they can be odd voltages (0.9V). This can cause transistors that are connected to them to be "half on" causing weird behavior if the transistors power devices (thermal camera, modems)
=> GPIO boot config

salt/server/tools/map.jinja
The version of mc we were using seems to have a bug which triggers when verifying that a copy to Catalyst Cloud succeeded.
=> Upgrade mc to prevent errors during backup uploads

pi/thermal-recorder/thermal-recorder.yaml.jinja
If the new cacophony:continuous-recording is set to true
thermal-recorder will recording continuously (up to the max-secs
limit).
This is useful for capturing everything that's going on. To be used
for tuning motion detection.
=> Add support for continuous recording

pi/config.txt.jinja
- Lowered to 50kH from the default 100kH. 
- Lepton camera and RTC look to still work at this speed
=> Lower the i2c speed to 50kH to prevent errors when talking to the attiny

pi/thermal-recorder/init.sls
Removed now-unused thermal-recorder watches.
Tested on pi with `salt-call --local state.apply pi/thermal-recorder`
Not relevant.
=> Removed now-unused thermal-recorder watches

pi/salt-minion/check-salt-keys, pi/salt-minion/check-salt-keys.cron, pi/salt-minion/init.sls, pi/salt-minion/override.conf
Added new check-salt-keys helper which will delete the salt minion's key files if they are empty.
This is called every hour as well as just before the salt-minion starts. The salt-minion will be restarted by the hourly check if a problem is found.
See https://trello.com/c/flexPujq/639-if-salt-minion-key-files-are-empty-delete-and-restart-minion
Developed and tested on a pi with `salt-call --local`
N.A.
=> Repair salt-minion keys if required

pi/salt-minion/minion
This supports troubleshooting for failed upgrades and salt issues generally.
Developed and tested on pi. Ran salt command from master to confirm relevant logs are being generated.
N.A.
=> Increase the salt minion log level to info

pi/maybe-reboot.sls
If a reboot is required after an update completes, delay it by a minute.
This means the salt master gets to see the result of the state.apply
instead of it looking that the command never completed.
Tested on pi using `salt-call --local`
N.A.
=> Don't reboot immediately when required

pi/salt-minion/minion
- Turn down console log level to avoid doubled up logging
- Turn off scheduler logs to avoid uninteresting log spam
Tested on a dev pi. Ran salt jobs to confirm desired output.
N.A.
=> Minion logging tweaks

_modules/cacophony.py
This allows us to easily turn continuous recording on and off. For
example, to turn on continuous recording:
```
salt camera123 cacophony.continuous_recording True
```
Developed and tested on a pi.
Not required.
=> Add cacophony.continuous_recording helper

pi/config/init.sls
Pull in battery defaults changes.
Visual only.
N.A.
=> Bump go-config to 1.2.0

server/hosts.jinja
This allow csalt and other clients to connect to the API server from inside the datacentre.
Manual testing on a server.
N.A.
=> Include hosts entry for API server in prod

.github/pull_request_template.md, pi/end/init.sls, pi/start/init.sls, pi/start/stay-on, pi/start/stay-on.service, salt/.gitignore, salt/top.sls, state-apply-test.sh
When running a salt state.apply "stay-on" requests will go to `attiny-controller` and `modemd` to keep the device on and internet up while the device is updating
- Added `state-apply-test.sh` This can be used to help with testing salt changes on a device.
https://github.com/TheCacophonyProject/saltops/pull/154
=> Add stay on requests

server/basics.sls
libopenal is required by ffmpeg.
Manually tested on server-test-processing
N.A.
=> Keep libopenal - it's required by ffmpeg

pi/rtc/fake-hwclock.service, pi/rtc/init.sls
Manage the fake-hwclock service file to what it is by default.
Previously we didn't want the fake-hwclock running in parallel to the RTC software as we were worried with it conflicting but fake-hwclock will only update the system time forward and not backwards. This means it shouldn't conflict with the RTC software we have running.
Tested the clock on my device in multiple conditions, no RTC, no internet, no internet or RTC.
NA
=> Manage fake-hwclock service file

pi/97-cacophony.conf, pi/basics.sls
Will write data to disk more often (sync) to reduce the logs lost when power is lost.
Tested on my device by pulling the power when looking at the logs (/var/log/syslog) over ssh.
With the default settings I tested it three times and lost 8s, 12s, 19s of logs.
With the new settings I lost 5s, 2s, 2s of logs.
No noticeable power change with the new settings.
NA
=> Write to disk more often to reduce data loss

pi/feverscreen/init.sls, pi/feverscreen/update-feverscreen, pi/feverscreen/update-feverscreen-beta
Add feverscreen package repo.
To add a device to the beta channel set the salt grain `fs-beta` to `true` by running `sudo salt-call  grains.append fs-beta true` on the device or from the salt server `sudo salt [deice-salt-id] grains.append fs-beta true`
To remove from the beta channel run `sudo salt-call  grains.delkey fs-beta` on the device or `sudo salt [deice-salt-id] grains.delkey fs-beta` from the salt server.
Note that the changes won't be applied until a salt update has run on the device.
Tested on my device but more testing is needed when we have to different releases on beta and main.
NA
=> Add feverscreen pkgrepo

pi/thermal-recorder/init.sls
On camera errors where the connection wasn't reset, leptond would resent the camera header info while thermal-recorder was expecting a frame.
=> thermal recorder hotfix

pi/thermal-recorder/init.sls
On camera errors where the connection wasn't reset, leptond would resent the camera header info while thermal-recorder was expecting a frame.
=> Update thermal recorder

pi/end/init.sls, pi/event-reporter.sls, pi/modemd/init.sls
- Update modemd to 1.2.2 This will change the default config letting the modem turn of when not used saving energy
- Update event reporter to 3.2.0 adding `version-reporter` that when run will send an event of the software that is install on the device. Gets automatically run on boot.
- Run `version-reporter` at end of salt update
NA
=> Add version reporter

pi/wpa.sls
- Fix bug where wpa settings for bushnet would get added multiple times
- Added wpa settings for `Bushnet` as lots of phone will capitalize the first letter of there hotspot 
Tested on mu device
NA
=> Fix bug with adding wpa settings multiple times. Added Bushnet wifi settings.

pi/thermal-recorder/init.sls
Thermal recorder background frame was including the edge pixels.This was causing processed to videos to have bad normalisation 
Tested on my pi locally and uploaded recordings to browse-test where they processed properly
=> updae thermal recorder

pi/dev-pis/init.sls, pi/prod-pis/init.sls, pi/test-pis/init.sls, salt/top.sls
Show what nodegroup was used by writing it to file.
Please include a references to any related PRs. https://github.com/TheCacophonyProject/saltops/pull/236
=> Show what nodegroup was used in update

_states/cacophony.py
When using the latest version of salt with python3 this causes some of the python code to error.
The changes makes it work with both python3 and 2
NA
=> Fix errors when using python3

pi/device-register.sls, pi/event-reporter.sls, pi/management-interface/init.sls
- Management-interface updated to 1.11.3
- event-reporter updated to 3.3.1
- device-register updated to 1.4.1
- These updates are so config events are created when a device registers or re-registers.
NA
=> Updated packges so events are created on rename

pi/attiny-controller/init.sls, pi/management-interface/init.sls, pi/thermal-recorder/init.sls
Attiny controller will now send heart beat events
Management interface will send camera preview over web socket, and thermal recorder will send frames over dbus to management interface rather than writing to a file.
=> update thermal rec, attiny and management

top.sls
Add support for cacophony-hosted apt repository
This is a top.sls change for master corresponding to changes in branch apt-repository
See linked pull request for details
- [ yes ] Does this change require an update to top.sls in the `master` branch?
- [ yes ] Has the relevant PR for the top.sls (including local `salt/top.sls`) been prepared
https://github.com/TheCacophonyProject/saltops/pull/275
=> Added apt-updater

pi/apt-updater/apt-updater-script
Add parameters to apt-get upgrade to run 'non-interactive, keep old config' where config clashes are detected during upgrade.
Pass and fail upgrade scenarios tested on stretch and bullseye RPis.
- [No ] Does this change require an update to top.sls in the `master` branch?
=> apt-ipdates - force non-interactive (retain old)

_states/cacophony.py
Version was of type unicode instead of string causing the assertion of type string to fail.
Tested using `state-apply-test-rpi.sh` on a device that had this bug.
NA
=> Fixes version string bug

top.sls
Removed `servers/salt` from test
Relevant PR: https://github.com/TheCacophonyProject/saltops/pull/318
=> removed 'servers/salt' from the test

top.sls
Removed `apt-updater` as it is not in use currently.
=> Removed apt-updater

pi/97-cacophony.conf, pi/basics.sls
Removed old config that caused more frequent SD card writes. Removing this will hopefully cause fewer SD cards to go corrupt.
NA
=> Removed sysconfig that made more frequent SD card writes

top.sls
For tc2 devices change from `thermal-recorder` to `thermal-recorder-py`
=> Change from thermal-recorder to thermal-recorder-py
